version: '2'
services:
  bot:
    build: .
    image: joanfont/dlc-bot
    links:
      - redis
    environment:
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
    env_file:
      - .env
    volumes:
      - ".:/code/"

  redis:
    image: library/redis:4.0.8
    expose:
      - 6379

